/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real float
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int inverse_dynamics_rnea(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int inverse_dynamics_rnea_alloc_mem(void);
int inverse_dynamics_rnea_init_mem(int mem);
void inverse_dynamics_rnea_free_mem(int mem);
int inverse_dynamics_rnea_checkout(void);
void inverse_dynamics_rnea_release(int mem);
void inverse_dynamics_rnea_incref(void);
void inverse_dynamics_rnea_decref(void);
casadi_int inverse_dynamics_rnea_n_in(void);
casadi_int inverse_dynamics_rnea_n_out(void);
casadi_real inverse_dynamics_rnea_default_in(casadi_int i);
const char* inverse_dynamics_rnea_name_in(casadi_int i);
const char* inverse_dynamics_rnea_name_out(casadi_int i);
const casadi_int* inverse_dynamics_rnea_sparsity_in(casadi_int i);
const casadi_int* inverse_dynamics_rnea_sparsity_out(casadi_int i);
int inverse_dynamics_rnea_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int inverse_dynamics_rnea_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define inverse_dynamics_rnea_SZ_ARG 3
#define inverse_dynamics_rnea_SZ_RES 1
#define inverse_dynamics_rnea_SZ_IW 0
#define inverse_dynamics_rnea_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
